"""FastAPI router for chat API endpoints."""

import json
import logging
from collections.abc import AsyncIterator

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.chat.service import ChatService, ChatServiceError
from src.database import get_db
from src.models.models import Conversation, Message
from src.models.schemas import (
    ChatMessageRequest,
    ConversationCreate,
    ConversationResponse,
    MessageResponse,
)

logger = logging.getLogger(__name__)

router = APIRouter()


def _get_chat_service(db: AsyncSession) -> ChatService:
    """Create a ChatService instance.

    This is separated to allow easier error handling for missing API keys.
    """
    try:
        return ChatService(db)
    except ChatServiceError as e:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(e),
        )


@router.post(
    "/conversations",
    response_model=ConversationResponse,
    status_code=status.HTTP_201_CREATED,
)
async def create_conversation(
    conversation_data: ConversationCreate,
    db: AsyncSession = Depends(get_db),
) -> Conversation:
    """Create a new conversation for a model.

    The model_id must reference an existing architecture model.
    """
    # Validate model exists
    service = _get_chat_service(db)
    try:
        await service.validate_model_exists(conversation_data.model_id)
    except ChatServiceError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(e),
        )

    # Create conversation
    conversation = Conversation(
        model_id=conversation_data.model_id,
        title=conversation_data.title,
    )
    db.add(conversation)
    await db.commit()
    await db.refresh(conversation)

    return conversation


@router.get("/conversations", response_model=list[ConversationResponse])
async def list_conversations(
    model_id: str,
    db: AsyncSession = Depends(get_db),
) -> list[Conversation]:
    """List conversations for a model.

    The model_id query parameter is required.
    """
    result = await db.execute(
        select(Conversation)
        .where(Conversation.model_id == model_id)
        .order_by(Conversation.updated_at.desc())
    )
    return list(result.scalars().all())


@router.get("/conversations/{conversation_id}", response_model=ConversationResponse)
async def get_conversation(
    conversation_id: str,
    db: AsyncSession = Depends(get_db),
) -> Conversation:
    """Get a conversation by ID."""
    result = await db.execute(
        select(Conversation).where(Conversation.id == conversation_id)
    )
    conversation = result.scalar_one_or_none()
    if conversation is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Conversation {conversation_id} not found",
        )
    return conversation


@router.get(
    "/conversations/{conversation_id}/messages",
    response_model=list[MessageResponse],
)
async def list_messages(
    conversation_id: str,
    db: AsyncSession = Depends(get_db),
) -> list[Message]:
    """List messages in a conversation."""
    # Verify conversation exists
    conv_result = await db.execute(
        select(Conversation).where(Conversation.id == conversation_id)
    )
    if conv_result.scalar_one_or_none() is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Conversation {conversation_id} not found",
        )

    result = await db.execute(
        select(Message)
        .where(Message.conversation_id == conversation_id)
        .order_by(Message.created_at.asc())
    )
    return list(result.scalars().all())


async def _stream_sse_events(
    service: ChatService,
    conversation: Conversation,
    user_message: str,
) -> AsyncIterator[str]:
    """Stream SSE events from the chat service.

    SSE format:
    event: <type>
    data: <json-data>

    """
    async for event in service.stream_response(conversation, user_message):
        # Format as SSE
        event_type = event.type
        event_data = json.dumps(event.data) if event.data is not None else ""

        yield f"event: {event_type}\ndata: {event_data}\n\n"


@router.post("/conversations/{conversation_id}/messages")
async def send_message(
    conversation_id: str,
    message_data: ChatMessageRequest,
    db: AsyncSession = Depends(get_db),
) -> StreamingResponse:
    """Send a message to a conversation and stream the response.

    This endpoint returns a Server-Sent Events (SSE) stream with the following events:

    - `token`: Text chunks as they are generated by the LLM
    - `operations`: Parsed operations array from the LLM response
    - `graph`: Updated graph state after applying operations
    - `error`: Error message if something fails
    - `done`: Signals the end of the stream
    """
    # Get conversation
    result = await db.execute(
        select(Conversation).where(Conversation.id == conversation_id)
    )
    conversation = result.scalar_one_or_none()
    if conversation is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Conversation {conversation_id} not found",
        )

    # Create service
    service = _get_chat_service(db)

    # Return SSE stream
    return StreamingResponse(
        _stream_sse_events(service, conversation, message_data.content),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",  # Disable nginx buffering
        },
    )
