"""initial_schema_projects_models_nodes_edges

Revision ID: 9e87832a7778
Revises: 
Create Date: 2026-01-22 22:44:28.033192

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9e87832a7778'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_cloud', sa.String(length=50), nullable=True),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('iac_tool', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index('ix_models_project_id', ['project_id'], unique=False)

    op.create_table('nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('parent_node_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('size', sa.Text(), nullable=True),
    sa.Column('cost', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_node_id'], ['nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index('ix_nodes_model_id', ['model_id'], unique=False)
        batch_op.create_index('ix_nodes_parent_node_id', ['parent_node_id'], unique=False)

    op.create_table('edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('source_node_id', sa.String(length=36), nullable=False),
    sa.Column('target_node_id', sa.String(length=36), nullable=False),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.create_index('ix_edges_model_id', ['model_id'], unique=False)
        batch_op.create_index('ix_edges_source_node_id', ['source_node_id'], unique=False)
        batch_op.create_index('ix_edges_target_node_id', ['target_node_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_index('ix_edges_target_node_id')
        batch_op.drop_index('ix_edges_source_node_id')
        batch_op.drop_index('ix_edges_model_id')

    op.drop_table('edges')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index('ix_nodes_parent_node_id')
        batch_op.drop_index('ix_nodes_model_id')

    op.drop_table('nodes')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index('ix_models_project_id')

    op.drop_table('models')
    op.drop_table('projects')
    # ### end Alembic commands ###
